// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OCRPSystemWebAPI.Model;

namespace OCRPSystemWebAPI.Migrations.OCRP_System
{
    [DbContext(typeof(OCRP_SystemContext))]
    [Migration("20230426115140_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OCRPSystemWebAPI.Model.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Category_ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnName("Category_Name")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.HasKey("CategoryId");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("OCRPSystemWebAPI.Model.Recipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Recipe_Id")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnName("Category_ID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnName("Image_Url")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("Ingredients")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<string>("RecipeStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Recipe_status")
                        .HasColumnType("varchar(10)")
                        .HasDefaultValueSql("('Pending')")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.Property<string>("RecipeSteps")
                        .HasColumnName("Recipe_steps")
                        .HasColumnType("varchar(max)")
                        .IsUnicode(false);

                    b.Property<int?>("Serves")
                        .HasColumnType("int");

                    b.Property<int>("StateId")
                        .HasColumnName("State_ID")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<int>("UserId")
                        .HasColumnName("User_ID")
                        .HasColumnType("int");

                    b.HasKey("RecipeId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("StateId");

                    b.HasIndex("UserId");

                    b.ToTable("Recipe");
                });

            modelBuilder.Entity("OCRPSystemWebAPI.Model.State", b =>
                {
                    b.Property<int>("StateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("state_ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("StateName")
                        .IsRequired()
                        .HasColumnName("State_Name")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.HasKey("StateId");

                    b.ToTable("State");
                });

            modelBuilder.Entity("OCRPSystemWebAPI.Model.Users", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("User_ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EmailId")
                        .IsRequired()
                        .HasColumnName("Email_Id")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(false);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnName("User_Name")
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255)
                        .IsUnicode(false);

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnName("User_Type")
                        .HasColumnType("varchar(10)")
                        .HasMaxLength(10)
                        .IsUnicode(false);

                    b.HasKey("UserId")
                        .HasName("PK__Users__206D9190ED116D69");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("OCRPSystemWebAPI.Model.Recipe", b =>
                {
                    b.HasOne("OCRPSystemWebAPI.Model.Category", "Category")
                        .WithMany("Recipe")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK__Recipe__Category__46E78A0C")
                        .IsRequired();

                    b.HasOne("OCRPSystemWebAPI.Model.State", "State")
                        .WithMany("Recipe")
                        .HasForeignKey("StateId")
                        .HasConstraintName("FK__Recipe__State_ID__48CFD27E")
                        .IsRequired();

                    b.HasOne("OCRPSystemWebAPI.Model.Users", "User")
                        .WithMany("Recipe")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Recipe__User_ID__47DBAE45")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
